dropchance: 5
drops:
    50:
        stone:
            ==: org.bukkit.inventory.ItemStack
            type: STONE
            amount: 64
        wool:
            ==: org.bukkit.inventory.ItemStack
            type: WOOL
            amount: 16
        iron:
            ==: org.bukkit.inventory.ItemStack
            type: IRON_ORE
            amount: 16
        log:
            ==: org.bukkit.inventory.ItemStack
            type: LOG
            damage: 1
            amount: 64
    30:
        potion1:
            ==: org.bukkit.inventory.ItemStack
            type: POTION
            damage: 8230
        cake:
            ==: org.bukkit.inventory.ItemStack
            type: CAKE
        quartz:
            ==: org.bukkit.inventory.ItemStack
            type: QUARTZ_ORE
            amount: 23
        potion2:
            ==: org.bukkit.inventory.ItemStack
            type: POTION
            damage: 8226
        brick:
            ==: org.bukkit.inventory.ItemStack
            type: BRICK
            amount: 32
        lapis:
            ==: org.bukkit.inventory.ItemStack
            type: LAPIS_ORE
            amount: 11
        watch:
            ==: org.bukkit.inventory.ItemStack
            type: WATCH
    10:
        pods:
            ==: org.bukkit.inventory.ItemStack
            type: DIRT
            damage: 2
            amount: 64
        potion3:
            ==: org.bukkit.inventory.ItemStack
            type: POTION
            damage: 8235
        jukebox:
            ==: org.bukkit.inventory.ItemStack
            type: JUKEBOX
        iron_chest:
            ==: org.bukkit.inventory.ItemStack
            type: IRON_CHESTPLATE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        PROTECTION_ENVIRONMENTAL: 4
              repair-cost: 1
        potion4:
            ==: org.bukkit.inventory.ItemStack
            type: POTION
            damage: 8258
        iron_boots:
            ==: org.bukkit.inventory.ItemStack
            type: IRON_BOOTS
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        PROTECTION_ENVIRONMENTAL: 2
                        PROTECTION_FALL: 3
              repair-cost: 3
        rod:
            ==: org.bukkit.inventory.ItemStack
            type: FISHING_ROD
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        LURE: 1
                        LUCK: 3
              repair-cost: 3
    5:
        enerald:
            ==: org.bukkit.inventory.ItemStack
            type: EMERALD_ORE
            amount: 4
        diamond_spade:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_SPADE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        DURABILITY: 3
                        DIG_SPEED: 4
              repair-cost: 3
    3:
        diamond_axe:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_AXE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        DIG_SPEED: 4
              repair-cost: 1
        nametag:
            ==: org.bukkit.inventory.ItemStack
            type: NAME_TAG
        diamond_helmet:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_HELMET
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        WATER_WORKER: 1
              repair-cost: 1
    1:
        diamond_pick:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_PICKAXE
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        SILK_TOUCH: 1
              repair-cost: 1
        diamond_boots:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_BOOTS
            meta:
              ==: ItemMeta
              meta-type: UNSPECIFIC
              enchants:
                        PROTECTION_FALL: 4
              repair-cost: 1
        diamond_ore:
            ==: org.bukkit.inventory.ItemStack
            type: DIAMOND_ORE
            amount: 3
        skull:
            ==: org.bukkit.inventory.ItemStack
            type: SKULL_ITEM
            damage: 1